<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>authorization</title>
        <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="/assets/css/style.css">
    </head>
    <body>
    	<form action="/authorization" method="post">
			<h2></h2>
			<div class="myWidthForInput marginForInput form-group">
				<label for="login">Телефон или email</label>
				<input type="text" name="login" placeholder="login" class="form-control" required>
			</div>
			<div class="myWidthForInput marginForInput form-group">
				<label for="password">Пароль</label>
				<input type="password" name="password" placeholder="password" class="form-control" required>
			</div>
			<input type="submit" name="submit" value="Войти" class="btn btn-primary marginForInput">
			<a href="/register"><input type="btn" name="register" value="Зарегистрироваться" class="btn btn-primary marginForInput"></a> 
		</form>
    </body>
</html>    