<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>TODOLIST</title>
        <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    </head>
    <body>
    	<div class="btn-group btn-group-justified">
			<a href="http://host1.local/authorization" class="btn btn-primary">Login</a>
			<a href="http://host1.local/register" class="btn btn-primary">SignUp</a>
		</div>
        <h3>Добро пожаловать в ваш индивидуальный список заданий</h3>
        <div></div>
    </body>
</html>
