<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>register</title>
        <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="/assets/css/style.css">
    </head>
    <body>
    	<form action="/register" method="post">
			<h2></h2>
			<div class="myWidthForInput marginForInput form-group">
				<label for="login">Введите номер телефона или email</label>
				<input type="text" name="login" placeholder="login" class="form-control" required>
			</div>
			<div class="myWidthForInput marginForInput form-group">
				<label for="password">Введите пароль</label>
				<input type="password" name="password" placeholder="password" class="form-control">
			</div>
			<input type="submit" name="register" value="Зарегистрироваться" class="btn btn-primary marginForInput"> 
		</form>
    </body>
</html>    